export interface Articulo {
  otrosF1: string,
  otrosN1: number,
  otrosN2: number,
  otrosC1: string,
  otrosC2: string,
  otrosC3: string,
  otrosC4: string,
  otrosT1: string,
  usuario: number,
  equipo: string,
  id: number,
  nombre: string,
  descripcion: string,
  codigo: string,
  codigoArticulo: string,
  codigoModelo: string,
  codigoBarra: string,
  codigoGrupo: number,
  codigoColor: number,
  codigoTalla: number,
  codigoTipoArticulo: number,
  codigoImpuesto: number,
  peso: number,
  volumen: number,
  metroCubico: number,
  pie: number,
  manejaLote: boolean,
  manejaSerial: boolean,
  poseeGarantia: boolean,
  descripcionGarantia: string,
  manejaPuntoMinimo: boolean,
  puntoMinimo: number,
  manejaPuntoMaximo: boolean,
  puntoMaximo: number,
  suspendido: boolean,
  presentaciones: number[] | number,
  fechaRegistro: string;
  usuarioRegistroNombre: string;
  fechaModificacion: string;
  usuarioModificacionNombre: string;
  imagen?: string;
  precio?: number;
  stock?: number;
}