export interface ArticuloPresentaciones {
    id: number,
    codigoArticulo: number,
    codigoPresentacion: number,
    esPrincipal: boolean,
    equivalencia: number,
    usarEnVentas: boolean,
    usarEnCompras: boolean,
    otrosF1: string,
    otrosN1: number,
    otrosN2: number,
    otrosC1: string,
    otrosC2: string,
    otrosC3: string,
    otrosC4: string,
    otrosT1: string,
    fechaRegistro: string,
    usuarioRegistroNombre: string,
    fechaModificacion: string,
    usuarioModificacionNombre: string    
}
